export const MINUS_DATA = "MINUS_DATA";
export const PLUS_DATA = "PLUS_DATA";
export const FETCH_DATA = "FETCH_DATA";
export const SET_FETCH_DATA = "SET_FETCH_DATA";

export const REQUEST_FETCH_DATA = "REQUEST_FETCH_DATA";
export const SUCCESS_FETCH_DATA = "SUCCESS_FETCH_DATA";
export const FAIL_FETCH_DATA = "FAIL_FETCH_DATA";

export const REQUEST_MEME_DATA = "REQUEST_MEME_DATA";
export const SUCCESS_MEME_DATA = "SUCCESS_MEME_DATA";
export const FAIL_MEME_DATA = "FAIL_MEME_DATA";

export const DISPLAY_NEW_DATA_WITH_CLICK = "DISPLAY_NEW_DATA_WITH_CLICK";
